export const languageOptions = [
  { id: 45, label: 'Assembly (NASM 2.14.02)', value: 'assembly-nasm', monacoLanguage: 'assembly' },
  { id: 46, label: 'Bash (5.0.0)', value: 'bash-5.0', monacoLanguage: 'bash' },
  { id: 47, label: 'Basic (FBC 1.07.1)', value: 'basic-fbc', monacoLanguage: 'basic' },
  { id: 48, label: 'C (GCC 7.4.0)', value: 'c-gcc7', monacoLanguage: 'c' },
  { id: 49, label: 'C (GCC 8.3.0)', value: 'c-gcc8', monacoLanguage: 'c' },
  { id: 50, label: 'C (GCC 9.2.0)', value: 'c-gcc9', monacoLanguage: 'c' },
  { id: 51, label: 'C# (Mono 6.6.0.161)', value: 'csharp-mono6', monacoLanguage: 'csharp' },
  { id: 52, label: 'C++ (GCC 7.4.0)', value: 'cpp-gcc7', monacoLanguage: 'cpp' },
  { id: 53, label: 'C++ (GCC 8.3.0)', value: 'cpp-gcc8', monacoLanguage: 'cpp' },
  { id: 54, label: 'C++ (GCC 9.2.0)', value: 'cpp-gcc9', monacoLanguage: 'cpp' },
  { id: 55, label: 'Common Lisp (SBCL 2.0.0)', value: 'lisp-sbcl', monacoLanguage: 'lisp' },
  { id: 56, label: 'D (DMD 2.089.1)', value: 'd-dmd', monacoLanguage: 'd' },
  { id: 57, label: 'Elixir (1.9.4)', value: 'elixir-1.9', monacoLanguage: 'elixir' },
  { id: 58, label: 'Erlang (OTP 22.2)', value: 'erlang-22', monacoLanguage: 'erlang' },
  { id: 59, label: 'Fortran (GFortran 9.2.0)', value: 'fortran-gfortran9', monacoLanguage: 'fortran' },
  { id: 60, label: 'Go (1.13.5)', value: 'go-1.13', monacoLanguage: 'go' },
  { id: 61, label: 'Haskell (GHC 8.8.1)', value: 'haskell-ghc8', monacoLanguage: 'haskell' },
  { id: 62, label: 'Java (OpenJDK 13.0.1)', value: 'java-openjdk13', monacoLanguage: 'java' },
  { id: 63, label: 'JavaScript (Node.js 12.14.0)', value: 'javascript-node12', monacoLanguage: 'javascript' },
  { id: 64, label: 'Lua (5.3.5)', value: 'lua-5.3', monacoLanguage: 'lua' },
  { id: 65, label: 'OCaml (4.09.0)', value: 'ocaml-4.09', monacoLanguage: 'ocaml' },
  { id: 66, label: 'Octave (5.1.0)', value: 'octave-5.1', monacoLanguage: 'octave' },
  { id: 67, label: 'Pascal (FPC 3.0.4)', value: 'pascal-fpc3', monacoLanguage: 'pascal' },
  { id: 68, label: 'PHP (7.4.1)', value: 'php-7.4', monacoLanguage: 'php' },
  { id: 69, label: 'Prolog (GNU Prolog 1.4.5)', value: 'prolog-gnu', monacoLanguage: 'prolog' },
  { id: 70, label: 'Python (2.7.17)', value: 'python-2.7', monacoLanguage: 'python' },
  { id: 71, label: 'Python (3.8.1)', value: 'python-3.8', monacoLanguage: 'python' },
  { id: 72, label: 'Ruby (2.7.0)', value: 'ruby-2.7', monacoLanguage: 'ruby' },
  { id: 73, label: 'Rust (1.40.0)', value: 'rust-1.40', monacoLanguage: 'rust' },
  { id: 74, label: 'TypeScript (3.7.4)', value: 'typescript-3.7', monacoLanguage: 'typescript' },
  { id: 75, label: 'C (Clang 7.0.1)', value: 'c-clang7', monacoLanguage: 'c' },
  { id: 76, label: 'C++ (Clang 7.0.1)', value: 'cpp-clang7', monacoLanguage: 'cpp' },
  { id: 77, label: 'Cobol (GnuCOBOL 2.2)', value: 'cobol-gnucobol2', monacoLanguage: 'cobol' },
  { id: 78, label: 'Kotlin (1.3.70)', value: 'kotlin-1.3', monacoLanguage: 'kotlin' },
  { id: 79, label: 'Objective-C (Clang 7.0.1)', value: 'objective-c-clang7', monacoLanguage: 'objective-c' },
  { id: 80, label: 'R (4.0.0)', value: 'r-4.0', monacoLanguage: 'r' },
  { id: 81, label: 'Scala (2.13.2)', value: 'scala-2.13', monacoLanguage: 'scala' },
  { id: 82, label: 'SQL (SQLite 3.27.2)', value: 'sql-sqlite3', monacoLanguage: 'sql' },
  { id: 83, label: 'Swift (5.2.3)', value: 'swift-5.2', monacoLanguage: 'swift' },
  { id: 84, label: 'VB.NET (Mono 6.6.0.161)', value: 'vbnet-mono6', monacoLanguage: 'vbnet' },
  { id: 85, label: 'Perl (5.28.1)', value: 'perl-5.28', monacoLanguage: 'perl' },
  { id: 86, label: 'Clojure (1.10.1)', value: 'clojure-1.10', monacoLanguage: 'clojure' },
  { id: 87, label: 'F# (Mono 6.6.0.161)', value: 'fsharp-mono6', monacoLanguage: 'fsharp' },
  { id: 88, label: 'Groovy (3.0.3)', value: 'groovy-3.0', monacoLanguage: 'groovy' },
  { id: 89, label: 'PowerShell (7.0.0)', value: 'powershell-7.0', monacoLanguage: 'powershell' },
  { id: 90, label: 'Scheme (Guile 2.2.6)', value: 'scheme-guile2', monacoLanguage: 'scheme' },
  { id: 91, label: 'Crystal (0.33.0)', value: 'crystal-0.33', monacoLanguage: 'crystal' },
  { id: 92, label: 'Julia (1.5.3)', value: 'julia-1.5', monacoLanguage: 'julia' },
  { id: 93, label: 'Nim (1.4.2)', value: 'nim-1.4', monacoLanguage: 'nim' },
  { id: 94, label: 'Racket (7.9)', value: 'racket-7.9', monacoLanguage: 'racket' },
  { id: 95, label: 'V (0.2.2)', value: 'vlang-0.2', monacoLanguage: 'vlang' },
  { id: 96, label: 'Zig (0.8.0)', value: 'zig-0.8', monacoLanguage: 'zig' },
  { id: 97, label: 'Ada (GNAT 9.2.0)', value: 'ada-gnat9', monacoLanguage: 'ada' },
  { id: 98, label: 'CoffeeScript (2.5.1)', value: 'coffeescript-2.5', monacoLanguage: 'coffeescript' },
  { id: 99, label: 'Dart (2.10.0)', value: 'dart-2.10', monacoLanguage: 'dart' },
];